#服务器的访问端口
server:
  port: 8090
spring:
  application:
    name: myweb01
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 1000
    database: 0
    pool:
      max-active: 10
      max-idle: 8
      min-idle: 2
      max-wait: 100
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/myweb01
    username: root
    password: 123456
    hikari:
      max-lifetime: 28830000 # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQL wait_timeout参数（show variables like '%timeout%';）
      maximum-pool-size: 9 # 连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
  rabbitmq:
    host: 120.55.56.15
    virtual-host: myVirtualHost01
    username: root
    password: 123456
    template:
      exchange: IExchange02
    publisher-confirms: true

  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 120.55.56.15:9300

#mapper的xml文件的扫描
mybatis:
  #对应实体类路径
  type-aliases-package: cn.myweb01.money01.pojo
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名
  #对应mapper映射文件路径,在resources文件夹下面
  mapper-locations: classpath:mappers/*.xml
logging:
  level:
    cn.myweb01.money01.mapper: DEBUG  #包路径为mapper文件包路径

#pagehelper物理分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  returnPageInfo: check



